name: CI/CD Pipeline

on: [push, pull_request, workflow_dispatch]

permissions:
  # allows SonarCloud to decorate PRs with analysis results
  pull-requests: read


jobs:
  MavenTest:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: maven

      - name: Format source code
        run: mvn formatter:format

      - name: Test with Maven
        run: mvn clean test

  SonarAnalysis:

      runs-on: ubuntu-latest

      steps:
          - name: Analyze with SonarCloud

            uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216

            env:
              # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            with:
              args:
                -Dsonar.projectKey=GreenCityProject_GreenCityUser21_team1
                -Dsonar.organization=greencityproject
                -Dsonar.binaries=target/classes
                -Dsonar.sources='src/main/java/greencity'