name: CI/CD Pipeline

on: [pull_request, workflow_dispatch]

permissions:
  pull-requests: read


jobs:
  Testing:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'oracle'
          cache: maven

      - name: Format source code
        run: mvn formatter:format

      - name: Test with Maven
        run: mvn clean test

      - name: Sonar Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run:
          mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=GreenCityProject_GreenCityUser21_team_1_May -Dsonar.organization=greencityproject -Dsonar.host.url=https://sonarcloud.io

#  SonarAnalysis:
#
#      runs-on: ubuntu-latest
#
#      steps:
#          - name: Analyze with SonarCloud
#            if: github.ref != 'refs/heads/disable-sonar-scan'
#
#            uses: SonarSource/sonarcloud-github-action@v2.2.0
#
#            env:
#              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#              SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#            with:
#              args:
#                -Dsonar.projectKey=GreenCityProject_GreenCityUser21_team1
#                -Dsonar.organization=greencityproject
#                -Dsonar.sources=.